# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Artifact Resolver"
  homepage: https://maven.apache.org/resolver/
  labels:
    - java
    - build-management
    - apache-maven
    - maven
  protected_branches:
    master: { }
    maven-resolver-1.9.x: { }
    maven-resolver-1.6.x: { }
  pull_requests:
    del_branch_on_merge: true
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  features:
    issues: true
notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org
project:
  metadata:
    key: maven-resolver
    committee: maven
    name: Apache Maven Resolver
    description: Apache Maven Resolver is a library for working with artifact repositories and dependency resolution.
    short_description: Apache Maven Resolver is a library for working with artifact repositories and dependency resolution.
    homepage: https://maven.apache.org/resolver/
    download_page: https://maven.apache.org/resolver/download.cgi
    bug_database: https://maven.apache.org/resolver/issue-management.html
    mailing_lists: https://maven.apache.org/resolver/mailing-lists.html
    repositories:
      - https://github.com/apache/maven-resolver
    categories:
      - build-management
    programming_languages:
      - Java
  policy:
    github_repository_name: maven-resolver
    download_path_suffix: resolver
  features:
    atr_sync: true
